CREATE TABLE USER (
    ID VARCHAR(15) PRIMARY KEY,
    USERNAME VARCHAR(31) NOT NULL
);

CREATE TABLE USER_KEY (
    ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(15) NOT NULL,
    HASHED_PASSWORD VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE USER_SESSION (
    ID VARCHAR(127) PRIMARY KEY,
    USER_ID VARCHAR(15) NOT NULL,
    ACTIVE_EXPIRES BIGINT NOT NULL,
    IDLE_EXPIRES BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);